version: '2'
services:
  ds:
    build: .
    command: watch -n1 "echo 'systems running'"
    volumes:
      - ./kubeconfig.sample:/root/.kube/config
      - .:/app
      - /app/node_modules

  ds2:
    build: .
    command: watch -n1 "echo 'systems running'"
    volumes:
      - ./kubeconfig.sample:/root/.kube/config
      - .:/app
      - /app/node_modules

  ds3:
    build: .
    command: watch -n1 "echo 'systems running'"
    volumes:
      - ./kubeconfig.sample:/root/.kube/config
      - .:/app
      - /app/node_modules
